#!/usr/bin/env sh

# Script to create a floating menu with alacritty and fzf

# Creating a window using the alacritty daemon is significantly faster
ALACRITTY="alacritty msg create-window"

fifo=$(mktemp -u)
infile=$(mktemp)
mkfifo "$fifo"
trap 'rm -f $fifo $infile' EXIT

# Capture stdin if piped into
[ ! -t 0 ] && cat > "$infile"

POINTER="${POINTER:--}"
$ALACRITTY \
    -o window.padding.x=20  \
    -o window.padding.y=20  \
    -T fzm --class fzm      \
    -e sh -c "
    fzf --color=bw --border=horizontal --reverse --pointer='$POINTER ' --no-scrollbar \
        --prompt='$POINTER ' --input-border=none --no-separator --multi --ellipsis='' \
    $( [ -s "$infile" ] && echo "< $infile") > $fifo
    " || {
        echo "Failed to create an alacritty window" >&2
        exit 1
    }

tac "$fifo"
